import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { inflateSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';

/**
 * The extension's toolbar icon.
 *
 * It is the one place the mark ships as a bitmap — Chrome takes no SVG for
 * `icons` or `action.default_icon` — so it is also the one place that cannot
 * be checked by reading the artwork. For a whole release the manifest declared
 * no icons at all and the extension wore Chrome's grey placeholder letter;
 * nothing here noticed, because nothing here looked.
 *
 * These read the pixels. The PNGs are generated by `icons.mjs` next door and
 * committed, so what they mostly guard against is the generator not having
 * been re-run. `pnpm acceptance:icons` asks a real Chrome the rest of it.
 */
const root = join(import.meta.dirname, '../..');
const manifest = JSON.parse(readFileSync(join(root, 'apps/extension/manifest.base.json'), 'utf8'));
const SIZES = [16, 32, 48, 128] as const;

/** The master drawing's ink, the same way brand.test.ts reads it. */
const TEAL = readFileSync(join(root, 'tools/brand/source.svg'), 'utf8')
  .match(/fill:\s*(#[0-9a-fA-F]{6})/)![1]!
  .toLowerCase();

type Pixels = { width: number; height: number; channels: number; data: Buffer };

/**
 * Just enough PNG to read a screenshot back: 8-bit truecolour with alpha, not
 * interlaced, which is what Chromium writes. Anything else throws rather than
 * being decoded wrongly and quietly passing.
 */
function decodePng(file: string): Pixels {
  const buf = readFileSync(file);
  expect(buf.subarray(0, 8).toString('latin1')).toBe('\x89PNG\r\n\x1a\n');

  let header: Buffer | undefined;
  const idat: Buffer[] = [];
  for (let at = 8; at < buf.length; ) {
    const length = buf.readUInt32BE(at);
    const type = buf.toString('ascii', at + 4, at + 8);
    const body = buf.subarray(at + 8, at + 8 + length);
    if (type === 'IHDR') header = body;
    if (type === 'IDAT') idat.push(body);
    at += 12 + length;
  }
  const ihdr = header!;
  const [width, height] = [ihdr.readUInt32BE(0), ihdr.readUInt32BE(4)];
  const [depth, colour, interlace] = [ihdr[8], ihdr[9], ihdr[12]];
  expect({ depth, colour, interlace }).toEqual({ depth: 8, colour: 6, interlace: 0 });

  const channels = 4;
  const stride = width * channels;
  const raw = inflateSync(Buffer.concat(idat));
  const data = Buffer.alloc(height * stride);
  // Undo the per-scanline filters. PNG spec 9.2; `a` is the pixel to the left,
  // `b` the one above, `c` the one above-left.
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)]!;
    const line = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    for (let x = 0; x < stride; x++) {
      const a = x >= channels ? data[y * stride + x - channels]! : 0;
      const b = y > 0 ? data[(y - 1) * stride + x]! : 0;
      const c = x >= channels && y > 0 ? data[(y - 1) * stride + x - channels]! : 0;
      let value = line[x]!;
      if (filter === 1) value += a;
      else if (filter === 2) value += b;
      else if (filter === 3) value += (a + b) >> 1;
      else if (filter === 4) {
        const p = a + b - c;
        const [pa, pb, pc] = [Math.abs(p - a), Math.abs(p - b), Math.abs(p - c)];
        value += pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
      }
      data[y * stride + x] = value & 0xff;
    }
  }
  return { width, height, channels, data };
}

const icons = new Map(SIZES.map((size) => [size, decodePng(join(root, `apps/extension/icons/icon-${size}.png`))]));
const pixel = ({ data, width, channels }: Pixels, x: number, y: number) => {
  const at = (y * width + x) * channels;
  return { r: data[at]!, g: data[at + 1]!, b: data[at + 2]!, a: data[at + 3]! };
};
const hex = (p: { r: number; g: number; b: number }) =>
  `#${[p.r, p.g, p.b].map((v) => v.toString(16).padStart(2, '0')).join('')}`;

describe('the manifest', () => {
  it('declares an icon at every size Chrome asks for', () => {
    // Without these the toolbar shows a grey letter, which is what shipped.
    const expected = Object.fromEntries(SIZES.map((size) => [String(size), `icons/icon-${size}.png`]));
    expect(manifest.icons).toEqual(expected);
    expect(manifest.action.default_icon).toEqual(expected);
  });
});

describe.each(SIZES)('icon-%dpx', (size) => {
  const icon = icons.get(size)!;

  it('is that many pixels square', () => {
    // The sizes are the manifest's keys, so a mis-sized file is a lie to Chrome.
    expect([icon.width, icon.height]).toEqual([size, size]);
  });

  it('leaves the corners transparent', () => {
    // An opaque icon sits in a visible box on the toolbar. The glyph is framed
    // with a little air for exactly this reason: at 16px one pixel covers 37
    // units of the drawing, and a tighter crop bled the hem into two of them.
    for (const [x, y] of [[0, 0], [size - 1, 0], [0, size - 1], [size - 1, size - 1]]) {
      expect(pixel(icon, x!, y!).a).toBe(0);
    }
  });

  it('is drawn in the ink of the master drawing', () => {
    // The glyph is the figure and nothing else, so every opaque pixel in it is
    // the ink — and it must still be the colour source.svg is drawn in.
    const seen = new Map<string, number>();
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const p = pixel(icon, x, y);
        if (p.a === 255) seen.set(hex(p), (seen.get(hex(p)) ?? 0) + 1);
      }
    }
    const [commonest] = [...seen].sort((a, b) => b[1] - a[1])[0]!;
    expect(commonest).toBe(TEAL);
  });

  it('actually has the jellyfish drawn in it', () => {
    // An empty file — the svg failing to load during rasterisation — passes
    // every check above, because nothing above insists on a pixel being there.
    // Measured at 0.39 to 0.45 across the four sizes; the bounds are wide
    // enough for the rasteriser to disagree and narrow enough to notice a
    // figure that vanished or one that grew into a filled tile.
    let ink = 0;
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        if (pixel(icon, x, y).a > 200) ink++;
      }
    }
    expect(ink / (size * size)).toBeGreaterThan(0.25);
    expect(ink / (size * size)).toBeLessThan(0.6);
  });
});

describe('the eyes', () => {
  /**
   * Counting colour changes along a row, rather than sampling where the eyes
   * are meant to be: a row through the face reads
   *
   *   squircle · body · face · eye · face · eye · face · body · squircle
   *
   * so it changes colour eight times. Lose the eyes — the bug this project has
   * already shipped once — and the most that row can manage is four. The glyph
   * is the figure on nothing rather than a figure in a tile, so the run reads
   * clear · body · face · eye · face · eye · face · body · clear instead, and
   * the count is the same.
   *
   * Only the top half is counted, and that is not tidiness. The first version
   * of this scanned the whole icon, and an eyeless icon passed it: the hem's
   * four scallops alternate leg and notch often enough to hit the same count
   * on their own. The face is at a third of the way down; the hem is at the
   * bottom; half is a clean line between them.
   */
  const runsAcross = ({ width, height, ...rest }: Pixels) => {
    let most = 0;
    for (let y = 0; y < Math.floor(height / 2); y++) {
      let runs = 0;
      let previous = '';
      for (let x = 0; x < width; x++) {
        const p = pixel({ width, height, ...rest }, x, y);
        const kind = p.a < 128 ? 'clear' : (p.r + p.g + p.b) / 3 > 190 ? 'light' : 'ink';
        if (kind !== previous) runs++;
        previous = kind;
      }
      most = Math.max(most, runs);
    }
    return most;
  };

  it.each(SIZES)('are separate from the face at %dpx', (size) => {
    expect(runsAcross(icons.get(size)!)).toBeGreaterThanOrEqual(9);
  });

  /*
   * 16px included, which it was not while the icon was the mark reversed out
   * of a squircle. The eyes are 44x65 units in a 598 unit drawing, and inside
   * that squircle they landed under a pixel and merged; the note here used to
   * record that as the size where losing them was allowed. Framed on its own
   * box the figure is about a third larger at the same 16px, and they survive.
   */
});
